### PR TITLE
Adding TurbineInit.stop() to shut down all thread pools

### PR DESCRIPTION
**Pull request by ahus1**
I found that Turbine doesn't shutdown all the thread pools it starts. 

I fixed all thread pools until Tomcat didn't complain any more. 

Please have a look. If you think something is missing, please comment.

Br Alexander.

### CODE REVIEW

**Comment by hmeerlo** [comment]
This is quite a big issue in my opinion. I can not imagine how a huge company like Netflix does not have a problem with this. Do they never undeploy/redeploy turbine?

**Comment by benjchristensen** [comment]
No we don't. The full application servers are always restarted as a whole. Also we don't have multi-tenant app servers for Turbine. It is a single Tomcat instance and always only Turbine on a given machine. 

At a higher level the machines Turbine run on are replaced every time anything is changed because all deployments are done via baking new Amazon Machine Images and launching new instances. 

Thus, the only time we 'shutdown' Turbine is killing it.

**Comment by hmeerlo** [comment]
Ok, that is indeed a reasonable explanation.Would love to be in such a situation, but unfortunately I have limited resources :-)

**Comment by benjchristensen** [comment]
It's less a matter of resources and more an architectural style. We use Amazon AWS for everything and thus all our "machines" are ephemeral. When we deploy new code we launch new instances and kill the old ones. 

You can see more about this model on this blog post: http://techblog.netflix.com/2013/03/ami-creation-with-aminator.html 

Here is a presentation that walks through the architecture: http://www.slideshare.net/adrianco/netflix-architecture-tutorial-at-gluecon

More here specifically on deployment: http://techblog.netflix.com/2013/08/deploying-netflix-api.html and http://www.slideshare.net/benjaminschmaus/gluecon-2013-netflix-api-crash-course

**Comment by ahus1** [comment]
@hmeerlo: feel free to give my pull request a try, and give +1 to get it integrated :-)

**Comment by hmeerlo** [comment]
+1
Just tested your pull request and it works perfect for me. For now I will deploy this into our local maven repo!

**Comment by opuneet** [comment]
@ahus1 Thanks for the PR. I'm looking into this, will get back to you soon. Thanks.

**Comment by ahus1** [comment]
@opuneet: please let me know if you need anything to accept this PR (i.e. tests, etc.)

**Comment by opuneet** [comment]
@ahus1  just merged this in. Apologies for the delay in getting to this.

**Pull request merged**
